### ISSUE TITLE
Hacktoberfest labels

### ISSUE THREAD

**Issue by Jacob3075** [swapnita-pandey/Data-Structures-and-Algorithms#18]
Can you add the hacktoberfest-accepted labels to the accepted PRs? 

Right now none of the the merged PRs submitted by everyone will be counted.

**Comment by Jacob3075** [comment]
If you are not going to  then can you mention that.
And why if possible.

**Comment by swapnita-pandey** [comment]
> Can you add the hacktoberfest-accepted labels to the accepted PRs?
> 
> Right now none of the the merged PRs submitted by everyone will be counted.

Done!
Thanks for reminding @Jacob3075 !

**Comment by Jacob3075** [comment]
Cool, thanks. 👍

**Comment by swapnita-pandey** [comment]
By the way!
I guess it's required only if your PR is not merged/accepted.
If your PR is merged, I guess the label is not required at all.

**Comment by swapnita-pandey** [comment]
The guidelines say:

A pull request can be approved either by giving it an overall approving review from maintainers, or by merging the pull request, or adding the 'hacktoberfest-accepted' label

**Comment by Jacob3075** [comment]
Even I saw that but when I logged in to check the PR status it showed as not accepted, that's why I asked.
After the labels were added it updated to waiting


Or it could have just been a delay when updating the status, idk

**Comment by swapnita-pandey** [comment]
Yes, it is delayed.
