### ISSUE TITLE
Kotlin code for Binary Tree

### ISSUE THREAD

**Issue by Jacob3075** [swapnita-pandey/Data-Structures-and-Algorithms#3]
Is this project fine with multiple languages?

**Comment by swapnita-pandey** [comment]
Yes, I am fine with multiple languages.
You can surely add @Jacob3075

**Comment by Jacob3075** [comment]
Hi, I noticed that you've not marked the merged PRs with the hacktoberfest-accepted label.
It would be nice if you'd add that otherwise it won't get accepted/counted.

**Comment by Jacob3075** [comment]
> Hi, I noticed that you've not marked the merged PRs with the hacktoberfest-accepted label.
> It would be nice if you'd add that otherwise it won't get accepted/counted. 

@swapnita-pandey
